apiVersion: 1

datasources:
  - name: SwiggyIt PostgreSQL
    type: postgres
    uid: swiggyit-postgres
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1700
    isDefault: true
    editable: false
